spring:
  mail:
    host: smtp.naver.com
    username: dnjsdyd0712@naver.com
    port: '465'
    properties:
      mail:
        smtp:
          ssl:
            enable: 'true'
          auth: 'true'
    password: 123456
  freemarker:
    cache: 'false'
  h2:
    console:
      path: /h2-console
      enabled: 'true'
  datasource:
    password: ''
    username: sa
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'
      fail-on-empty-beans: 'false'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
kakao:
  redirect:
    url: http://localhost:8080/api/kakaologin
  client:
    id: 06
jwt:
  secret: asdfd
