# airbnb-deploy.yml

name: test-deploy

on:
  push:
    branches: [master]

permissions:
  contents: read

env: # 새로 추가한 부분
  S3_BUCKET_NAME: ssgwan
  PROJECT_NAME: ssgwan

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./BE

    steps:
      # 이전 부분 생략

      # 새로 추가한 부분
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash
        working-directory: ${{ env.working-directory }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip
        working-directory: ${{env.working-directory}}